// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9lrmWB2dkMA3JZCFSjx0EN7iIDqQCDBs',
    appId: '1:713429972209:web:2c0e47073ce276a803e550',
    messagingSenderId: '713429972209',
    projectId: 'workia-f1234',
    authDomain: 'workia-f1234.firebaseapp.com',
    storageBucket: 'workia-f1234.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMHTEb0fG30U3NLaBQtZApQOJHzaHgV4',
    appId: '1:713429972209:android:1b02abd4b92e82a603e550',
    messagingSenderId: '713429972209',
    projectId: 'workia-f1234',
    storageBucket: 'workia-f1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVXP6F8lUxBggb_GqcM8RHZGVH_8BtiNg',
    appId: '1:713429972209:ios:671a73716427321403e550',
    messagingSenderId: '713429972209',
    projectId: 'workia-f1234',
    storageBucket: 'workia-f1234.firebasestorage.app',
    iosBundleId: 'com.sapinfhn.workia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVXP6F8lUxBggb_GqcM8RHZGVH_8BtiNg',
    appId: '1:713429972209:ios:27b348f7f490633003e550',
    messagingSenderId: '713429972209',
    projectId: 'workia-f1234',
    storageBucket: 'workia-f1234.firebasestorage.app',
    iosBundleId: 'com.example.anubisGpt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9lrmWB2dkMA3JZCFSjx0EN7iIDqQCDBs',
    appId: '1:713429972209:web:539aed406cfc159503e550',
    messagingSenderId: '713429972209',
    projectId: 'workia-f1234',
    authDomain: 'workia-f1234.firebaseapp.com',
    storageBucket: 'workia-f1234.firebasestorage.app',
  );

}